/* eslint-disable @typescript-eslint/naming-convention */
// Generated by https://quicktype.io

export interface MenusInterface {
    id:                number;
    name:      string;
    description: string;
    id_category:      number;
    price:      number;
    production_cost:  number;
    ingredients:      Ingrediente[];
    allergens:         string[];
    picture:      string;
}

export interface Ingrediente {
    name: string;
    quantity:           number;
}
